### PR TITLE
modified dbcp code due to connection disorder issues & singleton instance initialization

### PR DESCRIPTION
**Pull request by lucetre**
MYSQL* dbConn;
MYSQL conn;

DroneMap* DroneMap::instance = NULL;

### CODE REVIEW

**Review by upoque — CHANGES_REQUESTED** [review]
Nice work! Just a few remarks:
1. I still do not understand the need for a singleton object for DroneMap. Can you provide a reason to keep using this singleton structure?
2. Please remove binary files(x64/Debug... etc) from the commit. Also modify the .gitignore to stop track those files.

**Comment by lucetre** [comment]
1. I still do not understand the need for a singleton object for DroneMap. Can you provide a reason to keep using this singleton structure?
The singleton work was done by hexoul. DroneMap module is constructed only once so that we can access the database again unless we attempt to connect several times.

**Comment by hexoul** [comment]
Why did you add conn as member variable? it is never used.
Delete lines from 12 to 18. Don't include testing code.
If you need, make testing unit.

**Comment by hexoul** [comment]
Yes, I made it as Singleton because DroneMap class should be instantiated once.

**Comment by lucetre** [comment]
connection conn was originally used in

void DroneMap::connectDB()
{
	hasConnection = false;

	MYSQL conn;
	
	mysql_init(&conn);
 	dbConn = mysql_real_connect(&conn, DB_HOST, DB_USER, DB_PASS, DB_NAME, 3306, (char *)NULL, 0);

	if(dbConn != NULL) hasConnection = true;
}

There was a problem of connecting to db right after performing connectDB function like doQuery. There was no connections. So I thought it's because of local conn to I declared as a global variable.

**Comment by hexoul** [comment]
- Don't change the placement of "_H_DRONE_MAP_" declaration and ifndef. It is right.

- "char*" is not appropriate as parameter of getData function. you have to consider where getData wil be used. For example, (srcRowIdx, srcColIdx, dstRowIdx, dstColIdx) can be parameters for making query like "select * from where ROW >= srcRowIdx and ROW <= dstRowIdx ~".

- Originally MYSQL usage was wrong. Even the reason you said is right, you have to consider correct naming for that. I fixed this problem.

**Pull request closed without merging**
